name: Bump & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get latest commit message
        id: commit
        run: |
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine version bump type
        id: bump
        run: |
          msg="${{ steps.commit.outputs.msg }}"
          if [[ "$msg" =~ "#major" ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "$msg" =~ "#minor" ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: npm version ${{ steps.bump.outputs.type }}
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Push changes and tags
        run: |
          git push origin main
          git push origin --tags

      - name: Publish to npm
        run: npm publish --access public
